# ANN foundations
## Perceptron training using error-corrective learning

In [1]:
import numpy as np

### Functional output of a perception
$$ y = \sum{x_i.w_i} $$

In [2]:
# output functions
def functional_output(inputs, weights):
    return np.dot(inputs, weights)

In [3]:
functional_output([1, 2], [3, 4])

11

In [4]:
# activational output

def activation_function(output, threshold):
    if output >= threshold:
        return 1
    else:
        return 0

In [5]:
activation_function(-1, 1)

0

$$e = g- f$$

In [6]:
def error(activation, expected):
    assert len(activation) == len(expected), 'Dimension do not match'
    return np.subtract(expected, activation)

In [7]:
error([3, 2], [1, 1])

array([-2, -1])

In [8]:
def update_weights(x, error, learning_rate):
    return x * error * learning_rate

In [9]:
update = update_weights(1, 2, 1)

In [10]:
update

2

In [29]:
class SimpleNN:
    training_data = np.array([[-1, 1, 1, 1],
                             [-1, 1, 0, 0],
                             [-1, 0, 1, 0],
                             [-1, 0, 0, 0]])
    
    weights = np.array([0, 1, -1])
    
    learning_rate = 1
    
    threshold = 1
    
    input_data = training_data[:, [0, 1, 2]]
    
    desired_output = training_data[:, [3]].T[0]
    

In [30]:
snn = SimpleNN()

print("Training Data", snn.training_data)
print("Weights", snn.weights)
print("Learning rate", snn.learning_rate)
print("Threshold", snn.threshold)
print("Input Data", snn.input_data)
print("Desired Output", snn.desired_output)

Training Data [[-1  1  1  1]
 [-1  1  0  0]
 [-1  0  1  0]
 [-1  0  0  0]]
Weights [ 0  1 -1]
Learning rate 1
Threshold 1
Input Data [[-1  1  1]
 [-1  1  0]
 [-1  0  1]
 [-1  0  0]]
Desired Output [1 0 0 0]


In [31]:
y = np.array(functional_output(snn.input_data, snn.weights))
print(y)

[ 0  1 -1  0]


In [32]:
fy = np.array([activation_function(o, snn.threshold) for o in y])
print(fy)

[0 1 0 0]


In [33]:
err = error(fy, snn.desired_output)
print(err)

[ 1 -1  0  0]


In [34]:
# algorithm for training using error-corrective learning

w = snn.weights

counter = 0

while not np.array_equal(snn.desired_output, fy):
    print("Epoch", np.round(counter/4))
    
    print("weights     input     desired_output     actual_output     error     new_weight")
    
    for x in snn.input_data:
        
        y = np.array(functional_output(snn.input_data, w))
        
        fy = np.array([activation_function(o, snn.threshold) for o in y])
        
        err = error(fy, snn.desired_output)
        
        if(err[counter%4] == 0):
            print(w, "\t", x, "\t", snn.desired_output[counter%4], "\t\t\t", fy[counter%4],
                 "\t\t", err[counter%4], "\t", w, "no change")
        else:
            print(w, "\t", x, "\t", snn.desired_output[counter%4], "\t\t\t", fy[counter%4],
                 "\t\t", err[counter%4], "\t", w, "update weights")
            w = w + update_weights(snn.input_data[counter%4],
                                  err[counter%4], snn.learning_rate)
        counter += 1
        
print("Input data", snn.input_data)
print("Desired output", snn.desired_output)
print("Weights", w)
y = np.array(functional_output(snn.input_data, w))
fy = np.array([activation_function(o, snn.threshold) for o in y])
print("Actual output", fy)
err = error(fy, snn.desired_output)
print("Error", err)

Epoch 0.0
weights     input     desired_output     actual_output     error     new_weight
[ 0  1 -1] 	 [-1  1  1] 	 1 			 0 		 1 	 [ 0  1 -1] update weights
[-1  2  0] 	 [-1  1  0] 	 0 			 1 		 -1 	 [-1  2  0] update weights
[0 1 0] 	 [-1  0  1] 	 0 			 0 		 0 	 [0 1 0] no change
[0 1 0] 	 [-1  0  0] 	 0 			 0 		 0 	 [0 1 0] no change
Epoch 1.0
weights     input     desired_output     actual_output     error     new_weight
[0 1 0] 	 [-1  1  1] 	 1 			 1 		 0 	 [0 1 0] no change
[0 1 0] 	 [-1  1  0] 	 0 			 1 		 -1 	 [0 1 0] update weights
[1 0 0] 	 [-1  0  1] 	 0 			 0 		 0 	 [1 0 0] no change
[1 0 0] 	 [-1  0  0] 	 0 			 0 		 0 	 [1 0 0] no change
Epoch 2.0
weights     input     desired_output     actual_output     error     new_weight
[1 0 0] 	 [-1  1  1] 	 1 			 0 		 1 	 [1 0 0] update weights
[0 1 1] 	 [-1  1  0] 	 0 			 1 		 -1 	 [0 1 1] update weights
[1 0 1] 	 [-1  0  1] 	 0 			 0 		 0 	 [1 0 1] no change
[1 0 1] 	 [-1  0  0] 	 0 			 0 		 0 	 [1 0 1] no change
Epoch 3.0
weights 